### ISSUE TITLE
Crops do not use tool durability in EnderIO Farming Station

### ISSUE THREAD

**Issue by MemorableC** [TehNut-Mods/ResourcefulCrops#1]
The build that you gave me in the IRC (ResourcefulCrops-1.7.10-1.0.0-CUSTOM) does not use tool durability inside the farming station.

Tested by putting a wheat seed in the same farming station and it did use durability.
EnderIO is configured as comes with TPPI2 and I double checked to see that it was still set to use durability every time.

**Comment by TehNut** [comment]
I'm fairly sure I fixed this in dev, already.

[See here](https://github.com/TehNut/ResourcefulCrops/blob/1.7.10/src/main/java/tehnut/resourceful/crops/compat/enderio/ResourcefulCropsFarmer.java#L54)

**Comment by MemorableC** [comment]
Cool, i didn't have time to comb through the recent changes when i posted this and thought it wouldn't hurt to let you know.

**Comment by TehNut** [comment]
No worries.

I have noticed, however, that when you have no hoe in the Farming Station and it plants the crop on Farmland, it plants a null crop. Still working on a fix for that.

**Comment by TehNut** [comment]
Closing this and moving the one I mentioned to it's own issue.
