### ISSUE TITLE
A simple suggestion

### ISSUE THREAD

**Issue by ACGaming** [TehNut-Mods/ResourcefulCrops#11]
Hey there!

First, I have to say that ResourcefulCrops is simply awesome! The design is simple and straightforward yet very helpful, a good replacement for Magical Crops.
But there's one thing that bothers me quite a bit in comparison with Magical Crops: There is no way to self-sustain the source of all crops, Gaianite.
I know, you can edit it in easily through configs and that's what I did. But I'd love to see this as a built-in feature in ResourcefulCrops!

Thanks for reading and keep it up! :)

**Comment by TehNut** [comment]
I left this out on purpose. The ability to grow the stuff that lets you grow anything in the game is too overpowered in my opinion to include it by default.

However, as of the latest build (or last build?) you can obtain Gaianite Ore (Nether and Normal) through the MFR Mining Laser using the Purple focus.. Albeit at a low chance.

**Comment by ACGaming** [comment]
Alright, good to know that from your side!

**Comment by TehNut** [comment]
I also forgot that ExNihilio sieves will drop the base essence, as well. So it's definitely self-sustainable, just not through itself.

**Comment by Furious1964** [comment]
Trying to add Gaianite to the list of ore mined by the Environmental Tech Void Miner and I'd like to know what I need to put in the config. Thanks.
