### ISSUE TITLE
server crash with custom seeds without metadata

### ISSUE THREAD

**Issue by Saereth** [TehNut-Mods/ResourcefulCrops#12]
If a custom entry is made such as ThermalFoundation:Ore#4 for input it will crash the server. 
ThermalFoundation:Ore:0#4 works fine. The meta is intended to be included as per the instructions (which I didnt notice until I started digging around the code for the crash issue). A more graceful way of handling the error may be a good enhancement for the mod in the future

**Comment by TehNut** [comment]
What is the crash exactly?

**Comment by TehNut** [comment]
Alright, it was just an out of bounds exception.

With this commit, it'll swallow the crash and print an error to the log:

`LogHelper.error("Error adding " + (input ? "inputStack" : "outputStack") + ": " + stackString + ". Is it formatted correctly?");`
