### ISSUE TITLE
Server crash with MFR Harvester+Resourcefulcrops

### ISSUE THREAD

**Issue by Saereth** [TehNut-Mods/ResourcefulCrops#15]
This doesnt happen everytime, we've seen this crash about once a day now since the server has come up, enough to no longer consider it a fluke. Here is the full crashlog:

http://pastebin.com/J2cEvaFA

It seems to crash when it's being harvested by an MFR harvester.  

ResourcefulCrops-1.7.10-1.0.0-18 with
MineFactoryReloaded-[1.7.10]2.8.1B1-113

edit; crash has also been reported with enderio farming station when the tool runs out, possibly related to https://github.com/TehNut/ResourcefulCrops/issues/4 but not entirely sure if these are separate issues or not.

**Comment by TehNut** [comment]
Hm... I'll play with it when I get home 

EnderIO crash is also line 84 of BlockRCrop?

**Comment by Saereth** [comment]
Yes also line 84 with the farming station

**Comment by TehNut** [comment]
I'm just going to remove the ability to make "nether" seeds for now. It was a very poor implementation.

Under [heavy stress testing](http://gfycat.com/LegalWholeBrant), I am not able to reproduce the crash after removing the nether seeds. I didn't attempt prior, though. So unsure if issue is fixed..
