### ISSUE TITLE
API contains reference to package outside of API

### ISSUE THREAD

**Issue by InfinityRaider** [TehNut-Mods/ResourcefulCrops#16]
https://github.com/TehNut/ResourcefulCrops/blob/1.7.10/src/main/java/tehnut/resourceful/crops/api/util/helper/ItemHelper.java#L8

EDIT: also contains reference to external library (which I personally find quite annoying):
https://github.com/TehNut/ResourcefulCrops/blob/1.7.10/src/main/java/tehnut/resourceful/crops/api/util/cache/WorldCache.java#L9

**Comment by TehNut** [comment]
For the first thing: 

Oops.

For the second thing:

I forgot to setup the buildscript to de-lombok the API and deobf jars.

**Comment by TehNut** [comment]
Alright, try with build 20

**Comment by InfinityRaider** [comment]
Its fine, I removed the call to the debugger and replaced the @SneakyThrows annotations with try{} catch() {} statements, the code isn't compiled or runs during debugging, it just sits there being referenced by my code.
I thought I'd report it because others might run into this as well. I'll give it a go though.
