### ISSUE TITLE
OreDict crash in dev env

### ISSUE THREAD

**Issue by InfinityRaider** [TehNut-Mods/ResourcefulCrops#18]
I have this crahlog occurring in my dev env wiht ResourcefulCrops bulid 23: http://pastebin.com/BaMZYrHe
It only occurs in my dev env, both the obfuscated jar and the deobfuscated jar. It works fine in a regular mc instance. Forge is 1566.
The stacktrace points to MCForge code, so I'm not sure if I should report this here or on the Forge GitHub. Any thoughts?

**Comment by TehNut** [comment]
Solving all of these via Reddit PM with a modpack dev as we speak. :P

Delete the DefaultSeeds config and let it generate a new one

**Comment by InfinityRaider** [comment]
That did the trick, thanks for the support.

**Comment by TehNut** [comment]
No problem. These issues shouldn't have been a thing in the first case...

**Comment by InfinityRaider** [comment]
Don't worry about it, happens to everyone. Also now that I can properly debug, AgriCraft support will be coming very soon.

**Comment by TehNut** [comment]
\o/

I would have done it myself, but I've picked up a few too many modding projects to spend time on things that aren't drastically needed.
