### ISSUE TITLE
[1.7.10] Lighting glitch

### ISSUE THREAD

**Issue by bochen415** [TehNut-Mods/ResourcefulCrops#19]
Something weird is happening on the border of chunks. It depends on the plants growing just next to the glitched ones.
![2015-11-28_13 47 24](https://cloud.githubusercontent.com/assets/8314356/11451941/a5b80a3a-95d6-11e5-8fd7-1b6b0485a6f4.png)

My mods directory: [pic](http://i.imgur.com/Kn09LGM.png)
Forge 10.13.4.1558-1.7.10

.. also Iron Seeds? not Iron Plant/Crop?

**Comment by TehNut** [comment]
I have actually noticed this as well, but it's extremely rare and I can't reliably reproduce it.

> .. also Iron Seeds? not Iron Plant/Crop?

~~Go look at Wheat :p~~ I swear it used to say Wheat Seeds...

**Comment by InfinityRaider** [comment]
I had the same issue with my blocks, a single  `tessellator.setBrightness(block.getMixedBrightnessForBlock(world, x, y, z))` call in my rendering code fixed it. This prevents leaking of brightness setting form neighbouring blocks.

**Comment by TehNut** [comment]
Thanks! Here's hoping that fixes it. I know absolutely nothing about rendering...

**Comment by InfinityRaider** [comment]
Makes two of us...
