### ISSUE TITLE
Server loads json files in different order.

### ISSUE THREAD

**Issue by cloakable** [TehNut-Mods/ResourcefulCrops#21]
Okay, I've gotten to the root of my problem: I have three json files defining seeds (defaults, plus extras sorted into two tiers), and the server is loading them in a different order to the client, giving rise to a different list, hence the conflict. No idea what would cause this, though.

**Comment by TehNut** [comment]
This will be fixed when #9 finally gets resolved. For now, use a single file.

**Comment by TehNut** [comment]
Non-issue, as the new system condensed everything into a single file.
