### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by EXTER7** [TehNut-Mods/ResourcefulCrops#28]
[Crash report](http://pastebin.com/npKcw93f)

**Comment by TehNut** [comment]
Let me guess, `../config/ResourcefulCrops/Seeds-v2.json` is empty? Need to figure out _why_ that's happening...

**Comment by EXTER7** [comment]
Seems to be caused by OreDictionary.getOres() returning an empty list when called in [line 156 of StartupUtils.java](https://github.com/TehNut/ResourcefulCrops/blob/1.8.9/src/main/java/tehnut/resourceful/crops/util/StartupUtils.java#L156)

**Comment by TehNut** [comment]
... why would a valid oredict name be returning an empty list? I guess I'll add a check for that, then...
