### ISSUE TITLE
[1.9] Stones of creation during crafting give zero item then disapear

### ISSUE THREAD

**Issue by MCEventHorizon** [TehNut-Mods/ResourcefulCrops#32]
![2016-05-15_18 56 59](https://cloud.githubusercontent.com/assets/15619786/15275573/bbff7f02-1acf-11e6-884c-13c1fa06c103.png)

**Comment by TehNut** [comment]
Minecraft version? RCrops version? You gotta give me _some_ information.

**Comment by MCEventHorizon** [comment]
Latest Forge and Resourceful Crops for 1.9.
