### ISSUE TITLE
Is there a way to drop variable shards, seeds and/or gaianite?

### ISSUE THREAD

**Issue by mouseodoom** [TehNut-Mods/ResourcefulCrops#33]
Currently, each plant only drops one seed and shards. 

Is there a way to configure the number of shards that drop (say 0-2?) 

Same for seeds and gaianite?

Thanks for your attention and I really appreciate your work on this mod! It's fantastic!

**Comment by TehNut** [comment]
The closest you can get currently is by using the `"chance": {}` block. It's one of the un-documented ones, so no surprise that nobody knows about it...

Here's an example crop that uses every possible setting:

``` json
  "0": {
    "name": "IronOre",
    "tier": 3,
    "amount": 1,
    "input": "oreIron",
    "output": {
      "name": "minecraft:iron_ore",
      "amount": 1,
      "meta": 0
    },
    "color": "#0000FF",
    "secondOutput": {
      "name": "minecraft:iron_ingot",
      "amount": 1,
      "meta": 0
    },
    "thirdOutput": {
      "name": "minecraft:iron_block",
      "amount": 1,
      "meta": 0
    },
    "chance": {
      "extraSeed": 0.5,
      "essenceDrop": 0.7
    },
    "requirement": {
      "growthReq": {
        "name": "minecraft:lava",
        "meta": 0
      },
      "minDifficulty": "NORMAL",
      "lightLevelMin": 4,
      "lightLevelMax": 9
    }
  }
```

`extraSeed` and `essenceDrop` are both a percentage (`0.0` being 0%, `1.0` being 100%) chance to drop an extra seed or bit of Gaianite Essence respectively.

**Comment by mouseodoom** [comment]
Thank you! This is perfect!
