### ISSUE TITLE
ResourcefulCrops breaks when Pam's is installed with EasyHarvest

### ISSUE THREAD

**Issue by Mohron** [TehNut-Mods/ResourcefulCrops#34]
Version: ResourcefulCrops-1.9.4-1.3.2-54.jar
Pam's HC: Pam's HarvestCraft 1.9.4a.jar

When Pam's Harvestcraft is installed with ResourcefulCrops and enableEasyHarvest = true, ResourcefulCrops no longer drop an item when right-clicked.

Please see https://github.com/MatrexsVigil/harvestcraft/issues/120

**Comment by TehNut** [comment]
This is on her end.

**Comment by TehNut** [comment]
To expand: my crops require custom handling due to how they work. The "correct" methods do not work for me. Pam should be making checks before touching anything. 

I can (and probably will, as I have 0 faith in her) implement a bandaid on my end.

**Comment by Mohron** [comment]
Looks like you were right. The issue was just closed on the Pam's side without taking any action.

**Comment by TehNut** [comment]
Yup just saw that. I'll see what I can do to guard against it this weekend.
