### ISSUE TITLE
Recipes for custom seeds not generated

### ISSUE THREAD

**Issue by Teibidh** [TehNut-Mods/ResourcefulCrops#36]
I can't be 100% sure that this is a bug and not intended behavior but when I added custom seeds I expected to find recipes created for them with Gaianite requirements based on their tier and the common template. There are recipes generated to make the seed bags, but not ones to make the actual seeds.

I am using the 1.8.9 version, but as indicated elsewhere I reproduced in 1.10.2 prior to posting. My custom seeds seem to work fine otherwise, I can give myself seeds and plant them, and they grow and produce shards that wind up creating the right type of item. It's certainly possible I'm doing something wrong, but as it sits right now it looks like I may need to find another mod to add the recipes for the custom seeds?

**Comment by TehNut** [comment]
_Just_ custom ones don't get recipes? That is very odd... I handle all the recipes at the same time. 

E: Do you mean in JEI or do the recipes not work at all?

**Comment by ceiphas** [comment]
maybe the seed recipe is not working, because the input item wasn't found... 

look at the log file for something like:

[19:00:33] [Server thread/ERROR] [ResourcefulCrops]: Error adding inputStack: minecraft:dye#0. Is it formatted correctly?

**Comment by TehNut** [comment]
Should be fixed in 2.0 releases.
