### ISSUE TITLE
When connecting to my dev world (gradle started working copy) i am gifted 6 ink sacks...

### ISSUE THREAD

**Issue by ceiphas** [TehNut-Mods/ResourcefulCrops#39]
![2016-11-04_10 39 54](https://cloud.githubusercontent.com/assets/5346196/20001140/198114be-a27b-11e6-9f51-08b028459a50.png)

**Comment by ceiphas** [comment]
only the first time to open the inventory these show up, after that they are gone, but you can take and use them

**Comment by ceiphas** [comment]
I think it has something to do with the custom shard recipe not working

**Comment by TehNut** [comment]
What branch?

**Comment by ceiphas** [comment]
1.10... I added a dye seed Luke in magical crops with a custom recipe... In my 1.9 Branche that worked...

**Comment by ceiphas** [comment]
I hate german auto correction when typing english

**Comment by TehNut** [comment]
Should be fixed in 2.0 releases.
