### ISSUE TITLE
recipes are duplicated in JEI, as they are loaded everytie a world is loaded

### ISSUE THREAD

**Issue by ceiphas** [TehNut-Mods/ResourcefulCrops#40]
![2016-11-04_10 44 40](https://cloud.githubusercontent.com/assets/5346196/20001262/b5476088-a27b-11e6-887b-d7d7c6bb4cbe.png)

sometimes even a wrong output is created (i'm testing the custom shapes atm)

**Comment by TehNut** [comment]
Which branch is this on?

**Comment by ceiphas** [comment]
1.10

**Comment by TehNut** [comment]
Yeah I haven't added the recipe paging code yet. The 1.10 branch is still heavily WIP.
