### ISSUE TITLE
Invalid seeds cause crash on startup

### ISSUE THREAD

**Issue by ghost** [TehNut-Mods/ResourcefulCrops#42]
If you have seed configs with invalid ids, the game crashes on startup.

This is happens on its own if you add & remove other mods:

1) ResourcefulCrops adds configs for new mods automatically
2) You remove the other mod again
3) ResourcefulCrops auto-generated seed config stays
4) You now get a crash on startup as it can no longer find the material

This should not happen, it should just disregard the entry, log that and startup normally.

Both with ResourcefulCrops-1.10.2-2.0.0-56 and 57

**Comment by TehNut** [comment]
Can't do much without a log.

**Comment by ghost** [comment]
[crash-2017-03-06_10.44.37-client.txt](https://github.com/TehNut/ResourcefulCrops/files/821460/crash-2017-03-06_10.44.37-client.txt)
