### ISSUE TITLE
Client crash with hwyla/top

### ISSUE THREAD

**Issue by Darkere** [TehNut-Mods/ResourcefulCrops#47]
I'm not sure what happened but one of the players on the server started crashing upon join.
Looks to me like it has to do with #46 but you never know.

[Crash with hwyla](https://pastebin.com/8ZA6qBKs)
[Crash with Hwyla removed](https://pastebin.com/NqgRzEJ7)

Version 1.12 2.0.2-59

**Comment by Darkhax** [comment]
Can confirm, we are also having this issue on the ATC server. 

https://paste.ee/p/aNe7k

**Comment by TehNut** [comment]
Do you happen to know if you're looking at a crop for a seed that was removed?

**Comment by Darkhax** [comment]
I don't. This issue was from someone else. I believe Bambii.

**Comment by TehNut** [comment]
I put out a new build that attempts to fix it.

**Comment by VallenFrostweaver** [comment]
Recieving similar crash on 1.12 v2.0.2a-CUSTOM on the ATC server. Was using only tier 1 crops (feather, ink, rotten flesh).  Here's the crash report: https://pastebin.com/iLMB5CDL
