### ISSUE TITLE
Agricraft Compatibility

### ISSUE THREAD

**Issue by TehNut** [TehNut-Mods/ResourcefulCrops#5]
Need to look into it a bit more (Both the API and actually how Agricraft works).

[Agricraft API](https://github.com/InfinityRaider/AgriCraft/tree/master/src/main/java/com/InfinityRaider/AgriCraft/api)

**Comment by TehNut** [comment]
I do plan to have this generate defaults if Agricraft is loaded. So I'll need some mutations for the default crops.

@BBoldt Any ideas?

**Comment by BBoldt** [comment]
Check what the defaults are for the magical crops integration, those defaults were set by the agricraft creator so I see no reason to go against them too much.

In my pack I added some custom crops of my own, if you want to look at them for inspiration at all:
https://github.com/BBoldt/Unabridged/blob/master/scripts/Agricraft.zs
Not that many there though.

**Comment by TehNut** [comment]
Didn't realize MCrops had Agricraft compat. Will look through there, then.

[Compat](https://github.com/InfinityRaider/AgriCraft/tree/master/src/main/java/com/InfinityRaider/AgriCraft/compatibility/magicalcrops)

**Comment by InfinityRaider** [comment]
Hello I'm the creator of agricraft, I have added Magical Crops compat from my side, I've also looked to add compatibility for your mod from my side, but it appears you're using TileEntities for your crops so I think it'd be better to do it from your side.

You would have to register an ICropPlant (https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/api/v1/ICropPlant.java ) for every seed via the API: https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/api/v1/APIv1.java#L95

**Comment by TehNut** [comment]
Wonderful! Will look into that when I get a chance.

**Comment by InfinityRaider** [comment]
Implemented from my side: 
https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/compatibility/resourcefulcrops/ResourcefulCropsAPI.java
https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/compatibility/resourcefulcrops/CropPlantResourcefulCrops.java

Only have one little request, would it be possible to expose the Overlay IIcons to the API?

**Comment by TehNut** [comment]
Agricraft's implementation was released, closing.
