### ISSUE TITLE
Plant Gatherer from Industrial Foregoing makes null seeds

### ISSUE THREAD

**Issue by bochen415** [TehNut-Mods/ResourcefulCrops#55]
Using Plant Gatherer from [Industrial Foregoing](https://github.com/Buuz135/Industrial-Foregoing) results in null seeds.
![](https://i.imgur.com/qrbeHwd.png)

Recreated in a minimal environment:
ResourcefulCrops-1.12-2.1.1-62
MinecraftForge-1.12.2-14.23.0.2532
industrialforegoing-1.12.2-1.5.4-91
tesla-core-lib-1.12-1.0.11
Forgelin-1.5.1

https://gist.github.com/bochen415/f30a24258507a0b8791505450a90b373

**Comment by TehNut** [comment]
Issue with Forge introduced in https://github.com/MinecraftForge/MinecraftForge/commit/72f037b0fa5d3e02f14367ca86ae2ed9154126c8 which causes any mod calling only new method to get bad drops on blocks still overriding the old method.

**Comment by bochen415** [comment]
:+1: 
![](https://i.imgur.com/8RSA3G1.png)
