### ISSUE TITLE
Server/Client Data Syncing

### ISSUE THREAD

**Issue by TehNut** [TehNut-Mods/ResourcefulCrops#9]
Sync the Seed cache with the server on join. Client would dump it's list into a secondary list and pull in data from the server on join. When the client disconnects, cache the server's list locally (As `SERVERIP-Cache.dat` in `saves/cache/`) then bring it's original list back.

Would need to "versionize" server caches in case the server changes it's list.

Or something like that. I'unno.

**Comment by cloakable** [comment]
Any progress on this? I'm seeing conflicts in the seed cache between server and client, and deleting the client cache isn't fixing it for some reason.

**Comment by Mohron** [comment]
I think I'm having the same or a similar issue. When anyone connects to our server some of the seeds get switched around with another seed but not all do. For example Blaze and Slimey switch names and colors as well as the drops. The client and server configs are the default configs. Only happens when players connect to the server and does not happen in SSP.

Version: ResourcefulCrops-1.9.4-1.3.2-54.jar
Client json: http://pastebin.com/e9FFbBA3
Server json: http://pastebin.com/gdYcCS2p

**Comment by TehNut** [comment]
Hmm, in 1.9+ the syncing is all handled by Forge using the same system as blocks and items. I'll take a look tonight.

**Comment by Mohron** [comment]
@TehNut Let me know if I can provide anymore information that would help you find this bug.

**Comment by TehNut** [comment]
Hrm, could you load up a single player world and check the meta of the problem seeds, then check them again on the server?

I believe the problem is that I register recipes and OreDict entries for specific meta's, then when connecting to a server, those meta's get shuffled a bit with the recipes/entries keeping reference to the old meta.

**Comment by Mohron** [comment]
The problem disappears in single player and if you quit and then connect to a server, the problem returns. I had multiple people test it using our server.

**Comment by TehNut** [comment]
@Mohron Could you try with this build? I moved recipe registration around a bit. http://tehnut.info/share/ResourcefulCrops-1.9.4-1.3.2-CUSTOM.jar

**Comment by Mohron** [comment]
I put this build on my client and server. All recipes are missing JEI including the essence and Stones of creation.  I tested crafting with some of the shards and the crafting works but fails to show an output.

**UPDATE:** Just deleted the configs of both the client and server and let them generate on startup, same problem.

**Comment by TehNut** [comment]
Odd... The recipes showed up in my testing.

**Comment by Mohron** [comment]
I guess it could be a cross mod bug of some sort but I would ha no idea what could be causing an issue like this.

**Comment by TehNut** [comment]
How about this one?

http://tehnut.info/share/ResourcefulCrops-1.9.4-1.3.2-CUSTOM.jar

**Comment by Mohron** [comment]
That one on the other hand appears to work just fine!

**Comment by Vankka** [comment]
Had that same issue just when i added a seed

**Comment by Vankka** [comment]
Version: ResourcefulCrops-1.7.10-1.0.0-26

**Comment by TehNut** [comment]
1.7.10 is unsupported. 

Provide the same JSON to your clients as you do to your server.
